"""Tests for wing_parser.net.codec, driven by the 74 exchanges the console
actually sent (tests/data/wing_osc_fixtures.json) and the write-path
exchanges in tests/data/wing_write_fixtures.json. No hand-written bytes:
every assertion traces back to a captured hex string.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from wing_parser.net.codec import OscMessage, decode, encode, leaf_value

REPO_ROOT = Path(__file__).resolve().parents[1]
OSC_FIXTURES = json.loads(
    (REPO_ROOT / "tests" / "data" / "wing_osc_fixtures.json").read_text(encoding="utf-8")
)
WRITE_FIXTURES = json.loads(
    (REPO_ROOT / "tests" / "data" / "wing_write_fixtures.json").read_text(encoding="utf-8")
)
EXCHANGES = OSC_FIXTURES["exchanges"]


def fields_of(message: OscMessage) -> tuple[str, str | None, tuple]:
    """Turn a decoded message back into encode()'s argument shape.

    decode() reports a bare address-only reply as typetag="" (S2.1's older
    OSC form); encode()'s equivalent input is typetag=None. Everything else
    passes through unchanged.
    """
    typetag = message.typetag if message.typetag else None
    return message.address, typetag, message.args


# --- every non-null rx decodes to a well-formed message -------------------


@pytest.mark.parametrize("key", sorted(k for k, v in EXCHANGES.items() if v["rx"] is not None))
def test_every_captured_reply_decodes(key):
    entry = EXCHANGES[key]
    message = decode(bytes.fromhex(entry["rx"]))
    assert isinstance(message.address, str)
    assert message.address
    assert message.address.startswith("/")


# --- round trip: encode(*fields_of(decode(tx))) reproduces tx exactly -----

# Every tx in wing_osc_fixtures.json is a request the harness itself built,
# so it necessarily uses the minimal OSC padding encode() also produces --
# unlike two rx payloads in wing_write_fixtures.json (see below), nothing
# here was generated by the console itself. Covering every key exercises
# both address-only GETs (bare, typetag=None) and the one node-dump GET
# that carries a ,s "*" argument, plus the 4-segment vs. 2-segment address
# padding boundary.
@pytest.mark.parametrize("key", sorted(EXCHANGES.keys()))
def test_tx_round_trips_through_decode_and_encode(key):
    tx = bytes.fromhex(EXCHANGES[key]["tx"])
    message = decode(tx)
    assert encode(*fields_of(message)) == tx


# wing_write_fixtures.json's tx values are console-bound requests built the
# same way, so they round-trip too.
@pytest.mark.parametrize(
    "index", range(len(WRITE_FIXTURES)), ids=[e["label"] for e in WRITE_FIXTURES]
)
def test_write_fixture_tx_round_trips(index):
    tx = bytes.fromhex(WRITE_FIXTURES[index]["tx"])
    message = decode(tx)
    assert encode(*fields_of(message)) == tx


# Two rx payloads in wing_write_fixtures.json ("VALUE ERROR" and "NODE IS
# NOT PAR") are excluded from an rx round-trip test on purpose: their string
# argument's length already lands on a 4-byte boundary once the mandatory
# NUL terminator is added (11+1=12, 15+1=16), yet the console still appended
# a full extra 4-byte block of padding instead of the single terminator OSC
# requires. decode() reads the value correctly either way -- it stops at
# the first NUL -- but re-encoding with encode() produces the OSC-minimal
# padding, not the console's extra block, so those two payloads cannot
# round-trip byte-for-byte. Every other captured payload's trailing string
# either needs genuine padding (so the two forms coincide) or isn't last in
# the message, so this quirk is confirmed isolated to those two.
_RX_ROUNDTRIP_EXCLUDED = {"ERR bad value for enum", "ERR node is not par"}


@pytest.mark.parametrize(
    "index",
    [i for i, e in enumerate(WRITE_FIXTURES) if e.get("rx") is not None],
    ids=[e["label"] for e in WRITE_FIXTURES if e.get("rx") is not None],
)
def test_write_fixture_rx_round_trips(index):
    entry = WRITE_FIXTURES[index]
    if entry["label"] in _RX_ROUNDTRIP_EXCLUDED:
        pytest.skip("console over-pads this exact string length; see module docstring above")
    rx = bytes.fromhex(entry["rx"])
    message = decode(rx)
    assert encode(*fields_of(message)) == rx


# --- pinned triplet decoding, taken straight from the fixtures ------------


def _leaf(key: str) -> OscMessage:
    return decode(bytes.fromhex(EXCHANGES[key]["rx"]))


def test_fdr_is_sff_triplet_native_is_last_float():
    message = _leaf("get/ch/1/fdr")
    assert message.typetag == "sff"
    native, display = leaf_value(message)
    assert display == "-42.3"
    assert native == pytest.approx(-42.316715240478516)


def test_mute_is_sfi_triplet_native_is_last_int():
    message = _leaf("get/ch/1/mute")
    assert message.typetag == "sfi"
    native, display = leaf_value(message)
    assert display == "1"
    assert native == 1
    assert isinstance(native, int)


def test_in_conn_grp_is_lone_string():
    message = _leaf("get/ch/1/in/conn/grp")
    assert message.typetag == "s"
    native, display = leaf_value(message)
    assert native == "LCL"
    assert display == "LCL"


def test_flt_lcs_is_string_not_int():
    # design doc S2.3: the node-dump shows a bare 24, but the per-leaf
    # read keeps it as the string "24" -- never coerce it to int here.
    message = _leaf("get/ch/1/flt/lcs")
    assert message.typetag == "s"
    native, display = leaf_value(message)
    assert native == "24"
    assert isinstance(native, str)
    assert display == "24"


def test_eq_lq_native_float_is_bit_exact():
    message = _leaf("get/ch/1/eq/lq")
    assert message.typetag == "sff"
    native, display = leaf_value(message)
    assert display == "1.00"
    assert native == pytest.approx(0.9979702234268188)
