"""Tests for wing_parser.net.codec, driven by the 74 exchanges the console
actually sent (tests/data/wing_osc_fixtures.json) and the write-path
exchanges in tests/data/wing_write_fixtures.json. No hand-written bytes:
every assertion traces back to a captured hex string.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from wing_parser.net.codec import OscMessage, decode, encode, leaf_value

REPO_ROOT = Path(__file__).resolve().parents[1]
OSC_FIXTURES = json.loads(
    (REPO_ROOT / "tests" / "data" / "wing_osc_fixtures.json").read_text(encoding="utf-8")
)
WRITE_FIXTURES = json.loads(
    (REPO_ROOT / "tests" / "data" / "wing_write_fixtures.json").read_text(encoding="utf-8")
)
EXCHANGES = OSC_FIXTURES["exchanges"]

# Every recorded reply across both fixture files: (name, raw bytes). This is
# the same population design doc S2.7 measured (117 replies) when it
# characterised the `/*` error-reply over-padding quirk.
ALL_REPLIES: list[tuple[str, bytes]] = [
    (f"osc:{key}", bytes.fromhex(entry["rx"]))
    for key, entry in EXCHANGES.items()
    if entry["rx"] is not None
] + [
    (f"write:{entry['label']}", bytes.fromhex(entry["rx"]))
    for entry in WRITE_FIXTURES
    if entry.get("rx") is not None
]


def fields_of(message: OscMessage) -> tuple[str, str | None, tuple]:
    """Turn a decoded message back into encode()'s argument shape.

    decode() reports a bare address-only reply as typetag="" (S2.1's older
    OSC form); encode()'s equivalent input is typetag=None. Everything else
    passes through unchanged.
    """
    typetag = message.typetag if message.typetag else None
    return message.address, typetag, message.args


# --- every non-null rx decodes to a well-formed message -------------------


@pytest.mark.parametrize("key", sorted(k for k, v in EXCHANGES.items() if v["rx"] is not None))
def test_every_captured_reply_decodes(key):
    entry = EXCHANGES[key]
    message = decode(bytes.fromhex(entry["rx"]))
    assert isinstance(message.address, str)
    assert message.address
    assert message.address.startswith("/")


# --- round trip: encode(*fields_of(decode(tx))) reproduces tx exactly -----

# Every tx in wing_osc_fixtures.json is a request the harness itself built,
# so it necessarily uses the minimal OSC padding encode() also produces --
# unlike two rx payloads in wing_write_fixtures.json (see below), nothing
# here was generated by the console itself. Covering every key exercises
# both address-only GETs (bare, typetag=None) and the one node-dump GET
# that carries a ,s "*" argument, plus the 4-segment vs. 2-segment address
# padding boundary.
@pytest.mark.parametrize("key", sorted(EXCHANGES.keys()))
def test_tx_round_trips_through_decode_and_encode(key):
    tx = bytes.fromhex(EXCHANGES[key]["tx"])
    message = decode(tx)
    assert encode(*fields_of(message)) == tx


# wing_write_fixtures.json's tx values are console-bound requests built the
# same way, so they round-trip too.
@pytest.mark.parametrize(
    "index", range(len(WRITE_FIXTURES)), ids=[e["label"] for e in WRITE_FIXTURES]
)
def test_write_fixture_tx_round_trips(index):
    tx = bytes.fromhex(WRITE_FIXTURES[index]["tx"])
    message = decode(tx)
    assert encode(*fields_of(message)) == tx


# Two rx payloads in wing_write_fixtures.json ("VALUE ERROR" and "NODE IS
# NOT PAR") are excluded from this parametrization: design doc S2.7 (measured
# across all 117 recorded replies, corrected from an earlier draft that
# over-generalised the rule) establishes that the `/*` error-reply path pads
# those two payloads with one extra 4-byte NUL block that OSC 1.0 does not
# call for, so `encode()` -- which always emits OSC-1.0-minimal padding --
# cannot reproduce their exact bytes. decode() is unaffected (it stops at the
# first NUL) and the over-padding is asserted explicitly, not just skipped,
# in test_error_reply_over_padding_is_confined_to_two_known_cases below.
_RX_ROUNDTRIP_EXCLUDED = {"write:ERR bad value for enum", "write:ERR node is not par"}


@pytest.mark.parametrize(
    "index",
    [
        i
        for i, e in enumerate(WRITE_FIXTURES)
        if e.get("rx") is not None and f"write:{e['label']}" not in _RX_ROUNDTRIP_EXCLUDED
    ],
    ids=[
        e["label"]
        for e in WRITE_FIXTURES
        if e.get("rx") is not None and f"write:{e['label']}" not in _RX_ROUNDTRIP_EXCLUDED
    ],
)
def test_write_fixture_rx_round_trips(index):
    entry = WRITE_FIXTURES[index]
    rx = bytes.fromhex(entry["rx"])
    message = decode(rx)
    assert encode(*fields_of(message)) == rx


# --- the over-padding quirk itself: positive evidence, not a skip ---------

# design doc S2.7's two measured exceptions, by name and the ALL_REPLIES key
# that reaches them.
_OVER_PADDED = {
    "write:ERR bad value for enum": ("/*", "s", ("VALUE ERROR",)),
    "write:ERR node is not par": ("/*", "s", ("NODE IS NOT PAR",)),
}


@pytest.mark.parametrize("name", sorted(_OVER_PADDED))
def test_over_padded_error_replies_still_decode_correctly(name):
    """The extra NUL block sits past the last field, so decode() is unaffected.

    This is the positive claim design doc S2.7 makes about the quirk: it
    "costs nothing and breaks nothing" for decoding, proven here rather than
    asserted -- address, typetag and payload string all come out right.
    """
    rx = dict(ALL_REPLIES)[name]
    message = decode(rx)
    address, typetag, args = _OVER_PADDED[name]
    assert message.address == address
    assert message.typetag == typetag
    assert message.args == args


def test_over_padding_is_confined_to_exactly_the_two_known_error_replies():
    """Pin the scope of the quirk, not just its existence.

    design doc S2.7 corrects an earlier draft that guessed a general
    "string length is 3 mod 4" rule -- `cfg` (len 3) and `$syscfg` (len 7)
    both have that residue and both pad correctly. Measured across all 117
    recorded replies, the *only* two whose actual wire length exceeds what
    OSC 1.0's minimal-padding rule predicts are the two error payloads
    above, and both exceed it by exactly one NUL word (4 bytes) -- not some
    other amount. `encode(*fields_of(decode(rx)))` always emits the OSC-1.0
    minimal length, so comparing its length to the real reply length is
    exactly the "what does OSC 1.0 predict" oracle -- no separate padding
    arithmetic needs to be re-implemented here.
    """
    over_padded = {}
    for name, rx in ALL_REPLIES:
        message = decode(rx)
        predicted_length = len(encode(*fields_of(message)))
        delta = len(rx) - predicted_length
        if delta != 0:
            over_padded[name] = delta

    assert over_padded == {name: 4 for name in _OVER_PADDED}


def test_4k_minus_1_length_strings_in_non_final_position_all_decode_cleanly():
    """The 56-occurrence proof design doc S2.7 cites that the quirk cannot
    corrupt a multi-string reply: a string whose length is 3 mod 4 (the same
    residue class as the two over-padded payloads) that appears anywhere
    other than a message's last argument -- e.g. every entry in the `/io/in`
    or `/ch` node listings -- still decodes to exactly the text it should,
    because such a string is never the one the console over-pads.

    The proof is the byte-exact round trip: none of these 56 occurrences
    belongs to one of the two over-padded replies (those over-pad only their
    single, final argument), so every reply that contributes one is already
    covered by `test_tx_round_trips_through_decode_and_encode` /
    `test_write_fixture_rx_round_trips` on the request side, and is re-proven
    here directly on the reply bytes: had decode() mis-consumed a non-final
    field's padding, every field after it would be read from the wrong
    offset and the re-encoded message would not reproduce the original
    bytes.
    """
    occurrences = 0
    for name, rx in ALL_REPLIES:
        message = decode(rx)
        string_args = [
            (index, arg)
            for index, (tag, arg) in enumerate(zip(message.typetag, message.args))
            if tag == "s"
        ]
        last_index = len(message.typetag) - 1
        for index, arg in string_args:
            if index == last_index:
                continue
            if len(arg) % 4 == 3:
                occurrences += 1
                assert name not in _OVER_PADDED
                assert encode(*fields_of(message)) == rx

    assert occurrences == 56


# --- pinned triplet decoding, taken straight from the fixtures ------------


def _leaf(key: str) -> OscMessage:
    return decode(bytes.fromhex(EXCHANGES[key]["rx"]))


def test_fdr_is_sff_triplet_native_is_last_float():
    message = _leaf("get/ch/1/fdr")
    assert message.typetag == "sff"
    native, display = leaf_value(message)
    assert display == "-42.3"
    assert native == pytest.approx(-42.316715240478516)


def test_mute_is_sfi_triplet_where_display_and_native_agree():
    # display and native both say 1 here, so this alone proves nothing about
    # which argument leaf_value() should trust -- it only shows the common
    # case where the choice is invisible. The disagreeing case right below
    # is what actually pins the behaviour.
    message = _leaf("get/ch/1/mute")
    assert message.typetag == "sfi"
    value, display = leaf_value(message)
    assert display == "1"
    assert value == 1
    assert isinstance(value, int)


def test_in_conn_in_is_sfi_triplet_where_display_and_native_disagree():
    # design doc S2.3: a live push-then-read-back of user-files/example-Vu.snap
    # across 21000+ leaves found the .snap value matches the DISPLAY string
    # for every ,sfi leaf, not the trailing native int -- the native int is
    # often a 0-based index instead. This fixture is the recorded case that
    # proves it: the console's reply itself disagrees internally (display
    # '1', native 0), and leaf_value() must side with the display.
    message = _leaf("get/ch/1/in/conn/in")
    assert message.typetag == "sfi"
    assert message.args == ("1", 0.0, 0)  # the raw disagreement, from the wire
    value, display = leaf_value(message)
    assert display == "1"
    assert value == 1
    assert isinstance(value, int)


def test_in_conn_grp_is_lone_string():
    message = _leaf("get/ch/1/in/conn/grp")
    assert message.typetag == "s"
    native, display = leaf_value(message)
    assert native == "LCL"
    assert display == "LCL"


def test_flt_lcs_is_string_not_int():
    # design doc S2.3: the node-dump shows a bare 24, but the per-leaf
    # read keeps it as the string "24" -- never coerce it to int here.
    message = _leaf("get/ch/1/flt/lcs")
    assert message.typetag == "s"
    native, display = leaf_value(message)
    assert native == "24"
    assert isinstance(native, str)
    assert display == "24"


def test_eq_lq_native_float_is_bit_exact():
    message = _leaf("get/ch/1/eq/lq")
    assert message.typetag == "sff"
    native, display = leaf_value(message)
    assert display == "1.00"
    assert native == pytest.approx(0.9979702234268188)
