"""Regenerate the JSON-type oracle from the reference .snap files.

Run this, not the runtime, when a new reference scene arrives:

    python examples/generate_jsontypes.py

Why an oracle is needed at all, and why it is this small: a leaf read over
OSC carries its own type tag, and that tag settles almost everything.

    ,s    -> the value is a JSON string
    ,sff  -> the value is a JSON number, written without a trailing ".0"
             when it happens to be integral (WING's own convention: neither
             reference file contains a single ":N.0")
    ,sfi  -> the value is a JSON int OR a JSON bool, and the tag cannot say
             which

So the only thing the console cannot tell us is which integers a .snap file
writes as `true`/`false`. That set -- and nothing else -- is what this script
emits. Measured against a 600-leaf live sample, the rule above classified
every leaf correctly.

Paths are shape paths: numeric segments collapse to `*`, so `ch/7/eq/on`
and `ch/31/eq/on` share the entry `ch/*/eq/on`. `ce_data` is rooted at
`$ctl` to match the OSC address space.
"""

from __future__ import annotations

import collections
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REFERENCES = ("example-Vu.snap", "factory-scene.snap")
OUT = REPO / "wing_parser" / "net" / "data" / "wing_jsontypes.yaml"


def shape(parts: list[str]) -> str:
    return "/".join("*" if p.isdigit() else p for p in parts)


def walk(node, parts: list[str], seen: dict[str, set[str]]) -> None:
    if isinstance(node, dict):
        for key, value in node.items():
            walk(value, parts + [key], seen)
    else:
        seen[shape(parts)].add(type(node).__name__)


def main() -> int:
    seen: dict[str, set[str]] = collections.defaultdict(set)
    for name in REFERENCES:
        doc = json.loads((REPO / "user-files" / name).read_text(encoding="utf-8"))
        walk(doc["ae_data"], [], seen)
        walk(doc["ce_data"], ["$ctl"], seen)

    # A shape counts as boolean if either reference file ever wrote it as one.
    # Eighteen shapes -- the send `plink` family -- are `1` in example-Vu and
    # `true` in factory-scene, so WING is not self-consistent here. Both forms
    # mean the same thing and every consumer coerces with bool(), so taking
    # bool for those loses nothing; pretending the disagreement does not exist
    # would.
    booleans = sorted(path for path, kinds in seen.items() if "bool" in kinds)
    mixed = sorted(path for path, kinds in seen.items() if kinds == {"bool", "int"})

    lines = [
        "# Generated by examples/generate_jsontypes.py -- do not hand-edit.",
        "# Shape paths whose .snap representation is a JSON boolean. Every other",
        "# leaf type is recoverable from the OSC reply tag; see the script's",
        f"# docstring. Sources: {', '.join(REFERENCES)}.",
        f"# {len(mixed)} of these are written as 1/0 in one reference file and",
        "# true/false in the other; WING itself is inconsistent for them.",
        "booleans:",
    ]
    lines += [f"  - {path}" for path in booleans]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{len(seen)} shape paths examined")
    print(f"{len(booleans)} boolean shapes written to {OUT.relative_to(REPO)}")
    print(f"{len(mixed)} of them disagree between the two reference files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
