"""Every UI string lives in one place for future language switching."""

TEXTS: dict[str, str] = {
    "app.title": "wing",
    "page.doctor": "Doctor",
    "page.overview": "Overview",
    "page.channels": "Channels",
    "page.routing": "Routing",
    "page.diff": "Diff",
    "page.import": "Import",
    "empty.open_hint": "Open a scene file to begin.",
    "empty.open_button": "Open a scene...",
    "overview.counts": "Scene counts",
    "overview.channels": "Channels",
    "overview.buses": "Buses",
    "overview.mains": "Mains",
    "overview.matrices": "Matrices",
    "overview.live": "Live channels",
    "overview.named": "Named channels",
    "overview.anomalies": "Anomalies",
    "overview.table": "Channels",
    "overview.col.number": "Number",
    "overview.col.name": "Name",
    "overview.col.fader": "Fader",
    "overview.col.kind": "Kind",
    "channels.table": "Channels",
    "channels.col.number": "Number",
    "channels.col.name": "Name",
    "channels.col.kind": "Kind",
    "channels.col.confidence": "Confidence",
    "channels.col.fader": "Fader",
    "channels.col.muted": "Muted",
    "channels.detail_empty": "",
    "channels.title": "Channel {number}: {name}",
    "routing.summary": "Routing summary",
    "routing.col.label": "Item",
    "routing.col.value": "Count",
    "routing.unclassified": "Unclassified",
    "diff.compare": "Compare with...",
    "diff.clear": "Clear",
    "diff.table": "Differences",
    "diff.col.path": "Path",
    "diff.col.before": "Before",
    "diff.col.after": "After",
    "diff.col.magnitude": "Magnitude",
    "diff.no_session": "Open a scene first — it is the left side of the diff.",
    "diff.error": "Cannot read that file: {error}",
    "import.pick": "Pick a rundown (.xlsx)...",
    "import.sample_pane": "What is in this workbook",
    "import.sheet": "Sheet",
    "import.header_row": "Header row",
    "import.verified": "Model proposal verified",
    "import.unverified": "Model proposal unverified",
    "import.manual_hint": (
        "No model assist — name the sheet, header row and columns by hand."
    ),
    "import.back": "Back",
    "import.next": "Next",
    "import.load_guesses": "Load guesses",
    "import.record": "Record",
    "import.skip": "Skip",
    "import.preview": "Preview",
    "import.save_as": "Save As...",
    "import.error": "{error}",
    "import.needs_kind": "Type a kind before recording — never write a blank.",
}


def text(key: str) -> str:
    return TEXTS[key]
