"""Vietnamese mirror of `texts_moved.MOVED_TEXTS` (parity is tested)."""

MOVED_TEXTS_VI: dict[str, str] = {
    "verdict.correct": "Đúng",
    "verdict.false_positive": "Cảnh báo sai",
    "verdict.irrelevant": "Không liên quan",
    "verdict.none_yet": "{rule}: chưa có nhận định nào",
    "detail.none_recorded": "chưa có",
    "detail.why": "Vì sao có luật này",
    "detail.source": "Nguồn",
    "detail.evidence": "Bằng chứng",
    "findings.col.severity": "Mức độ",
    "findings.col.rule": "Luật",
    "findings.col.target": "Đối tượng",
    "findings.col.message": "Nội dung",
    "findings.col.layer": "Lớp",
    "findings.count_all": "{total} phát hiện",
    "findings.count_some": "{shown} trên {total} phát hiện",
    "import.sample_sheet": "SHEET {name}",
    "import.step.separator": "›",
    "token.all": "tất cả",
    "token.severity.error": "lỗi",
    "token.severity.warning": "cảnh báo",
    "token.severity.info": "thông tin",
    "token.layer.base": "cơ bản",
    "token.layer.toanaz": "toanaz",
    "token.layer.show": "show",
    "token.muted.yes": "Có",
    "token.muted.no": "Không",
    "token.match.exact": "chính xác",
    "token.match.word": "theo từ",
    "token.origin.default": "mặc định",
    "token.origin.manual": "tự thêm",
    "token.origin.default_edited": "mặc định, đã sửa",
}
