"""Records and comments become a YAML document.

ruamel rather than a hand-rolled emitter: the comments are the payload
here, and a hand-rolled one would need its own YAML scalar quoting, which
has silent edge cases (U+2028, an all-whitespace scalar) in new code
where existing code will do.

Every segment carries a real `cues: []`. It is true -- the sheet has no
cues -- the loader reads it as empty, and it gives a --scene proposal a
key to attach a comment before. Without it a segment has no key after
`expects:`, and ruamel has nothing to anchor to.
"""

from __future__ import annotations

import io

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

_INDENT = 4

_HEADER = """\
Generated by `wing showcontext import`. Read it before you use it.

Times and notes from the sheet are comments, not fields: nothing in this
tool reads a segment time, and a sheet's wall-clock time is not the
show-relative form `time:` accepts.

Only Q4 and Q5 fire on a file with no cues. Uncomment a proposed cue to
bring Q1, Q2, Q3 and Q6 to life for that segment. Q7 ships disabled
(base_rules/showcontext.yaml) and stays off regardless of cues.
"""


def _hashed(entry: str) -> list[str]:
    """Every physical line of `entry` gets its own leading `#`.

    The trailer is plain text, not a ruamel comment node -- nothing
    re-prefixes it for us the way `yaml_set_comment_before_after_key`
    re-prefixes every physical line of a row comment. This module makes
    no assumption that a caller has already escaped a real newline out
    of `entry`; a lone `f"# {entry}"` would let a second physical line
    fall out of the `#` block and be parsed as live YAML.
    """
    return [f"# {piece}" for piece in entry.split("\n")]


def _flow(values) -> CommentedSeq:
    seq = CommentedSeq(values)
    seq.fa.set_flow_style()
    return seq


def _segment(built, proposal: tuple[str, ...]) -> CommentedMap:
    item = CommentedMap()
    item["id"] = built.segment.id
    item["title"] = built.segment.title
    item["expects"] = _flow(list(built.segment.expects))
    item["cues"] = _flow([])
    if proposal:
        item.yaml_set_comment_before_after_key(
            "cues", before="\n".join(proposal), indent=_INDENT
        )
    return item


def render(show: str, result, proposals: dict[str, tuple[str, ...]] | None = None) -> str:
    proposals = proposals or {}

    doc = CommentedMap()
    doc["show"] = show
    doc.yaml_set_start_comment(_HEADER)

    segments = CommentedSeq()
    for index, built in enumerate(result.segments):
        segments.append(_segment(built, proposals.get(built.segment.id, ())))
        if built.comments:
            segments.yaml_set_comment_before_after_key(
                index, before="\n".join(built.comments), indent=_INDENT
            )
    doc["segments"] = segments

    engine = YAML()
    engine.indent(mapping=2, sequence=4, offset=2)
    engine.preserve_quotes = True
    engine.width = 4096
    buffer = io.StringIO()
    engine.dump(doc, buffer)
    text = buffer.getvalue()

    trailer = [""]
    if result.loose_comments:
        trailer.append("# rows kept as comments, not imported:")
        for entry in result.loose_comments:
            trailer.extend(_hashed(entry))
    trailer.append(
        f"# imported {result.data_rows} data row(s) -> "
        f"{len(result.segments)} segment(s), "
        f"{result.comment_rows} row(s) kept as comments, "
        f"{result.blank_rows} blank row(s) skipped"
    )
    return text + "\n".join(trailer) + "\n"
